'use client';

/* oxlint-disable next/no-img-element -- External mock images intentionally avoid production image configuration. */

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronRight, CircleAlert, Clipboard, Clapperboard as Instagram, ExternalLink, LoaderCircle, Map, MapPin, MoreHorizontal, Plus, Search, Sparkles, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Empty, EmptyContent, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from '@/components/ui/empty';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { baliPlaces, featuredPlace, mockRegions, type Place } from '@/lib/mock-data';

type Screen = 'home' | 'add' | 'analyzing' | 'result' | 'duplicate' | 'not-found' | 'candidates' | 'region';
type Scenario = 'success' | 'duplicate' | 'not-found' | 'candidates';
const sampleUrls: Record<Scenario, string> = {
  success: 'https://www.instagram.com/reel/C8mockplace/', duplicate: 'https://www.instagram.com/reel/duplicate/',
  'not-found': 'https://www.instagram.com/reel/not-found/', candidates: 'https://www.instagram.com/reel/candidates/',
};

function TopBar({ title, onBack }: { title: string; onBack: () => void }) {
  return <header className="mb-7 flex min-h-12 items-center gap-3"><Button variant="ghost" size="icon-lg" onClick={onBack} aria-label="Go back" className="-ml-2 rounded-full"><ArrowLeft /></Button><h1 className="text-xl font-semibold tracking-tight">{title}</h1></header>;
}
function Shell({ children }: { children: React.ReactNode }) {
  return <main className="min-h-screen px-5 pb-28 pt-7 sm:px-8"><div className="mx-auto w-full max-w-[430px]">{children}</div></main>;
}
function RegionCard({ region, onClick }: { region: (typeof mockRegions)[number]; onClick: () => void }) {
  return <button onClick={onClick} className="group flex min-h-20 w-full items-center gap-3 rounded-[1.25rem] border bg-card p-3 text-left shadow-[0_8px_28px_rgba(29,78,216,0.06)] transition hover:-translate-y-0.5 hover:border-primary/30 hover:shadow-[0_12px_32px_rgba(29,78,216,0.11)] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/30"><img src={region.image} alt="" className="size-14 shrink-0 rounded-xl object-cover" /><span className="min-w-0 flex-1"><span className="block text-lg font-bold tracking-tight text-foreground">{region.name}</span><span className="mt-1 flex items-center gap-1 text-sm font-medium text-muted-foreground"><MapPin className="size-3.5 text-primary" />{region.country}</span></span><span className="text-right"><span className="block text-lg font-bold text-primary">{region.count}</span><span className="block text-xs text-muted-foreground">places</span></span><ChevronRight className="size-5 text-primary/55 transition group-hover:translate-x-0.5 group-hover:text-primary" /></button>;
}
function HomeView({ onAdd, onRegion }: { onAdd: () => void; onRegion: () => void }) {
  const [empty, setEmpty] = useState(false);
  return <Shell><header className="mb-9"><div className="mb-3 flex items-center gap-2 text-sm font-semibold text-primary"><span className="grid size-8 place-items-center rounded-full bg-primary text-primary-foreground"><MapPin className="size-4" /></span>Reel Places</div><h1 className="text-[2.35rem] font-semibold leading-none tracking-[-0.05em]">Saved places</h1>{!empty && <p className="mt-3 text-base text-muted-foreground"><span className="font-semibold text-foreground">28</span> places across 3 regions</p>}</header>
    {empty ? <Empty className="min-h-[420px] border border-dashed bg-card/60"><EmptyHeader><EmptyMedia variant="icon" className="size-12 rounded-full bg-secondary text-primary"><MapPin /></EmptyMedia><EmptyTitle className="text-lg">No saved places yet</EmptyTitle><EmptyDescription>Found somewhere worth remembering? Paste its Instagram Reel and we’ll help you save it.</EmptyDescription></EmptyHeader><EmptyContent><Button onClick={onAdd} size="lg" className="h-12 rounded-xl px-5">Add your first place</Button></EmptyContent></Empty> : <section aria-labelledby="regions-heading"><div className="mb-4 flex items-center justify-between"><h2 id="regions-heading" className="text-sm font-semibold uppercase tracking-[0.14em] text-muted-foreground">Your regions</h2><button onClick={() => setEmpty(true)} className="text-sm text-muted-foreground underline-offset-4 hover:underline">Preview empty</button></div><div className="space-y-3">{mockRegions.map((region) => <RegionCard key={region.name} region={region} onClick={onRegion} />)}</div></section>}
    <button onClick={onAdd} aria-label="Add a place" className="fixed bottom-6 left-1/2 flex h-14 -translate-x-1/2 items-center gap-2 rounded-full bg-primary px-6 font-semibold text-primary-foreground shadow-[0_14px_35px_rgba(37,99,235,0.32)] transition hover:-translate-y-0.5 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/40"><Plus className="size-5" /> Add place</button></Shell>;
}
function AddView({ onBack, onAnalyze }: { onBack: () => void; onAnalyze: (scenario: Scenario) => void }) {
  const [url, setUrl] = useState(''); const [error, setError] = useState('');
  const analyze = () => { if (!/^https:\/\/(www\.)?instagram\.com\/reel(s)?\/[A-Za-z0-9_-]+\/?/.test(url)) { setError('Paste a valid Instagram Reel URL.'); return; } const scenario = (Object.entries(sampleUrls).find(([, value]) => value === url)?.[0] ?? 'success') as Scenario; onAnalyze(scenario); };
  const paste = async () => { try { const value = await navigator.clipboard.readText(); setUrl(value); setError(''); } catch { setUrl(sampleUrls.success); } };
  return <Shell><TopBar title="Add a place" onBack={onBack} /><div className="mb-8"><span className="mb-4 grid size-12 place-items-center rounded-2xl bg-secondary text-primary"><Instagram /></span><h2 className="text-[2rem] font-semibold leading-tight tracking-[-0.04em]">Paste a Reel.<br />We’ll find the place.</h2><p className="mt-3 text-base leading-relaxed text-muted-foreground">Copy the link from Instagram and paste it below.</p></div><label htmlFor="reel-url" className="mb-2 block text-sm font-semibold">Instagram Reel URL</label><div className={`flex rounded-2xl border bg-card p-1.5 shadow-sm transition focus-within:ring-4 focus-within:ring-ring/20 ${error ? 'border-destructive' : ''}`}><input id="reel-url" value={url} onChange={(e) => { setUrl(e.target.value); setError(''); }} placeholder="https://instagram.com/reel/..." className="min-w-0 flex-1 bg-transparent px-3 text-base outline-none placeholder:text-muted-foreground/65" /><Button variant="secondary" size="lg" className="h-11 rounded-xl" onClick={paste}><Clipboard /> Paste</Button></div>{error && <p className="mt-2 flex items-center gap-2 text-sm text-destructive"><CircleAlert className="size-4" />{error}</p>}<div className="mt-7 rounded-2xl bg-secondary/65 p-4"><p className="text-sm font-semibold">Try a mock state</p><div className="mt-3 flex flex-wrap gap-2">{(Object.keys(sampleUrls) as Scenario[]).map((item) => <button key={item} onClick={() => { setUrl(sampleUrls[item]); setError(''); }} className="min-h-10 rounded-full border bg-card px-3 text-sm font-medium capitalize hover:border-primary">{item.replace('-', ' ')}</button>)}</div></div><div className="fixed inset-x-0 bottom-0 border-t bg-background/90 p-4 backdrop-blur"><Button onClick={analyze} disabled={!url} className="mx-auto flex h-14 w-full max-w-[430px] rounded-2xl text-base">Analyze Reel <Sparkles /></Button></div></Shell>;
}
function AnalyzingView() { return <Shell><div className="flex min-h-[72vh] flex-col items-center justify-center text-center"><div className="relative mb-7 grid size-24 place-items-center rounded-[2rem] bg-secondary text-primary"><span className="absolute inset-0 animate-ping rounded-[2rem] bg-primary/10" /><LoaderCircle className="size-9 animate-spin" /></div><h1 className="text-2xl font-semibold tracking-tight">Finding this place…</h1><p className="mt-3 max-w-xs text-base leading-relaxed text-muted-foreground">Reading the Reel and matching details with our mock place library.</p><div className="mt-8 flex items-center gap-2 text-sm font-medium text-primary"><Check className="size-4" /> Reel link recognized</div></div></Shell>; }
function PlacePreview({ place }: { place: Place }) { return <article className="overflow-hidden rounded-[1.6rem] border bg-card shadow-[0_12px_40px_rgba(29,78,216,0.09)]"><div className="relative aspect-[16/9]"><img src={place.image} alt={`${place.name} in ${place.area}`} className="h-full w-full object-cover" /><Badge className="absolute left-4 top-4 h-8 rounded-full bg-card/95 px-3 text-primary shadow-sm"><Check className="size-3.5" /> Verified place</Badge></div><div className="p-5"><p className="mb-2 flex items-center gap-1.5 text-base font-semibold text-primary"><MapPin className="size-4" />{place.area}, {place.city}</p><h2 className="text-2xl font-bold leading-tight tracking-[-0.035em]">{place.name}</h2><p className="mt-2 text-sm font-medium text-muted-foreground">{place.category} · {place.country}</p><div className="mt-5 grid grid-cols-2 gap-2"><a href={place.instagramUrl} target="_blank" rel="noreferrer" className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-secondary text-sm font-semibold text-secondary-foreground"><Instagram className="size-4" />Instagram</a><a href={place.mapsUrl} target="_blank" rel="noreferrer" className="flex min-h-12 items-center justify-center gap-2 rounded-xl bg-secondary text-sm font-semibold text-secondary-foreground"><Map className="size-4" />Google Maps</a></div></div></article>; }
function ResultView({ onBack, onSave }: { onBack: () => void; onSave: () => void }) { return <Shell><TopBar title="Place found" onBack={onBack} /><PlacePreview place={featuredPlace} /><div className="fixed inset-x-0 bottom-0 border-t bg-background/90 p-4 backdrop-blur"><Button onClick={onSave} className="mx-auto flex h-14 w-full max-w-[430px] rounded-2xl text-base">Save place <ArrowRight /></Button></div></Shell>; }
function MessageView({ type, onBack, onRegion }: { type: 'duplicate' | 'not-found'; onBack: () => void; onRegion: () => void }) { const duplicate = type === 'duplicate'; return <Shell><TopBar title={duplicate ? 'Already saved' : 'No place found'} onBack={onBack} /><Empty className="min-h-[520px] border bg-card/70"><EmptyHeader><EmptyMedia variant="icon" className="size-14 rounded-full bg-secondary text-primary">{duplicate ? <Check /> : <Search />}</EmptyMedia><EmptyTitle className="text-xl">{duplicate ? 'This place is already in Bali' : 'We couldn’t identify a place'}</EmptyTitle><EmptyDescription>{duplicate ? 'WYAH Art & Creative Space is safely stored in your Ubud list.' : 'The Reel may not include enough location detail. Try another link or search manually later.'}</EmptyDescription></EmptyHeader><EmptyContent><Button onClick={duplicate ? onRegion : onBack} className="h-12 rounded-xl px-5">{duplicate ? 'View saved place' : 'Try another Reel'}</Button></EmptyContent></Empty></Shell>; }
function CandidatesView({ onBack, onSelect }: { onBack: () => void; onSelect: () => void }) { const candidates = [featuredPlace, { ...featuredPlace, id: 'wyah-resort', name: 'Wapa di Ume Ubud', category: 'Hotel' }]; return <Shell><TopBar title="Choose a place" onBack={onBack} /><p className="mb-5 text-base text-muted-foreground">We found two possible matches. Which one was in the Reel?</p><div className="space-y-3">{candidates.map((place, index) => <button key={place.id} onClick={onSelect} className="flex min-h-24 w-full items-center gap-4 rounded-2xl border bg-card p-3 text-left transition hover:border-primary"><img src={place.image} alt="" className="size-20 rounded-xl object-cover" /><span className="min-w-0 flex-1"><span className="block font-semibold">{place.name}</span><span className="mt-1 block text-sm text-muted-foreground">{place.category} · {place.area}</span><span className="mt-2 block text-xs font-medium text-primary">{index === 0 ? '94% match' : '68% match'}</span></span><ChevronRight className="size-5 text-muted-foreground" /></button>)}</div><Button variant="ghost" onClick={onBack} className="mt-5 h-12 w-full rounded-xl">None of these</Button></Shell>; }
function PlaceCard({ place }: { place: Place }) { return <article className="rounded-2xl border bg-card p-4 shadow-[0_6px_24px_rgba(29,78,216,0.06)]"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="mb-1.5 flex items-center gap-1.5 text-sm font-semibold text-primary"><MapPin className="size-4" />{place.area}, {place.city}</p><h3 className="text-[1.05rem] font-bold leading-snug tracking-tight text-foreground">{place.name}</h3><p className="mt-1 text-sm font-medium text-muted-foreground">{place.category}</p></div><img src={place.image} alt="" className="size-14 shrink-0 rounded-xl object-cover" /><DropdownMenu><DropdownMenuTrigger aria-label={`More options for ${place.name}`} className="grid size-10 shrink-0 place-items-center rounded-full hover:bg-muted"><MoreHorizontal className="size-5" /></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-44"><DropdownMenuItem><ExternalLink /> Open details</DropdownMenuItem><DropdownMenuItem variant="destructive"><Trash2 /> Delete place</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div><div className="mt-3 flex gap-5 border-t pt-2"><a href={place.instagramUrl} target="_blank" rel="noreferrer" className="flex min-h-9 items-center gap-1.5 text-sm font-semibold text-primary"><Instagram className="size-4" />Reel</a><a href={place.mapsUrl} target="_blank" rel="noreferrer" className="flex min-h-9 items-center gap-1.5 text-sm font-semibold text-primary"><Map className="size-4" />Maps</a></div></article>; }
function RegionView({ onBack }: { onBack: () => void }) { const groups = useMemo(() => Object.groupBy(baliPlaces, (place) => place.area), []); return <Shell><TopBar title="Bali" onBack={onBack} /><div className="mb-7 overflow-hidden rounded-[1.5rem] bg-primary p-5 text-primary-foreground"><p className="text-sm opacity-75">Indonesia</p><p className="mt-1 text-3xl font-semibold tracking-tight">12 saved places</p><p className="mt-4 text-sm opacity-75">Ready whenever Bali calls.</p></div><div className="space-y-8">{Object.entries(groups).map(([area, places]) => <section key={area}><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold">{area}</h2><span className="text-sm text-muted-foreground">{places?.length} places</span></div><div className="space-y-3">{places?.map((place) => <PlaceCard key={place.id} place={place} />)}</div></section>)}</div></Shell>; }

export function TravelApp() {
  const [screen, setScreen] = useState<Screen>('home');
  const analyze = (next: Scenario) => { setScreen('analyzing'); setTimeout(() => setScreen(next === 'success' ? 'result' : next), 950); };
  useEffect(() => { const context = document.modelContext; if (!context?.registerTool) return; const lifecycle = new AbortController(); void Promise.resolve(context.registerTool({ name: 'start_reel_analysis', title: 'Analyze Reel', description: 'Start the mock Reel analysis flow for a valid Instagram Reel URL.', inputSchema: { type: 'object', properties: { url: { type: 'string' }, scenario: { type: 'string', enum: ['success', 'duplicate', 'not-found', 'candidates'] } }, required: ['url'], additionalProperties: false }, annotations: { readOnlyHint: false, untrustedContentHint: true }, execute(input: unknown) { const data = input as { url?: string; scenario?: Scenario }; if (!data.url || !/^https:\/\/(www\.)?instagram\.com\/reel(s)?\//.test(data.url)) throw new Error('A valid Instagram Reel URL is required.'); analyze(data.scenario ?? 'success'); return { status: 'analyzing', url: data.url }; } }, { signal: lifecycle.signal })).catch(() => undefined); return () => lifecycle.abort(); }, []);
  if (screen === 'home') return <HomeView onAdd={() => setScreen('add')} onRegion={() => setScreen('region')} />;
  if (screen === 'add') return <AddView onBack={() => setScreen('home')} onAnalyze={analyze} />;
  if (screen === 'analyzing') return <AnalyzingView />;
  if (screen === 'result') return <ResultView onBack={() => setScreen('add')} onSave={() => setScreen('region')} />;
  if (screen === 'duplicate') return <MessageView type="duplicate" onBack={() => setScreen('add')} onRegion={() => setScreen('region')} />;
  if (screen === 'not-found') return <MessageView type="not-found" onBack={() => setScreen('add')} onRegion={() => setScreen('region')} />;
  if (screen === 'candidates') return <CandidatesView onBack={() => setScreen('add')} onSelect={() => setScreen('result')} />;
  return <RegionView onBack={() => setScreen('home')} />;
}
